### ISSUE TITLE
Emtpy string cannot be evaluated with 0.3.0

### ISSUE THREAD

**Issue by jlibovicky** [pltrdy/rouge#14]
When an empty string is passed a sentence to be evaluated (which can very easily happen at early stages of training a system), the scoring crashes in rouge/rouge.py, line 159.

```ipython
In [2]: import rouge
In [3]: rouge = rouge.Rouge()
In [4]: hyps = ['']
In [5]: ref = ['foo']
In [6]: rouge.get_scores(hyps, ref)
```

**Comment by pltrdy** [comment]
That's true. I guess I'll raise a custom error instead.   
I mean, my problem is that the exception isn't *that* relevant.   
The fact that an empty string cannot be evaluated, kind of make sense. ROUGE-N with empty string should return a kind of ValueError or Division by Zero.

**Comment by cholakov** [comment]
Hi @pltrdy,

I was having the same issue as @jlibovicky. Quite normally, an RNN produces hypotheses of zero length, especially in the first epochs. I wished I could tell `rouge` to just ignore empty lines rather than crash. In the end, I filtered out empty hypotheses with the code snippet below.

```
# Filter out hyps of 0 length
hyps_and_refs = zip(hyps, refs)
hyps_and_refs = [ _ for _ in hyps_and_refs if len(_[0]) > 0]
hyps, refs = zip(*hyps_and_refs)
```
Do you think it makes sense to add the script the main repo in the `Rouge` class? Perhaps line #L83 in `rouge.py`? We can alter the definition of `get_scores` to accept an extra binary argument `ignore_empty_hyps.`

We can change `FilesRouge` analogously.

I am happy to send you a pull request if you are cool with the changes.

**Comment by pltrdy** [comment]
My initial motivation for not doing this is that I prefer consider it an error by default. Hidding it could be missleading for people and really hard to debug, when just raising an error is annoying, but easy to fix. 

Still, we could add an `ignore_empty` for convenience, if we keep it off by default. Feel free to open an PR :)

**Comment by pltrdy** [comment]
(closed by PR: https://github.com/pltrdy/rouge/pull/18)
